apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: default
rules:
  - verbs:
      - get
      - watch
      - list
      - create
      - delete
      - update
    apiGroups: [""]
    resources:
      - pods