---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp-deployment
    tier: frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: myapp-deployment
      labels:
        tier: frontend
    spec:
      containers:
        - name: myapp-deployment
          image: nginx
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25
      maxSurge: 25

---
apiVersion: v1
kind: Service
metadata:
  name: canary-deployment-service
  labels:
    type: canary-example
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    tier: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deployment
  labels:
    tier: frontend
spec:
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: canary-deployment
      labels:
        tier: frontend
    spec:
      containers:
        - name: canary-deployment
          imagePullPolicy: IfNotPresent
          image: nginx
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25
      maxUnavailable: 25