---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    version: v2
    tier: frontend
    type: green
spec:
  selector:
    matchLabels:
      version: v2
      tier: frontend
  template:
    metadata:
      labels:
        version: v2
        tier: frontend
    spec:
      containers:
        - name: nginx-green-container
          image: nginx
          imagePullPolicy: Always
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: frontend-service
spec:
  selector:
    version: v2
    tier: frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080