apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    type: multi-container-pod-1
spec:
  containers:
    - name: simple-webapp
      image: kodekloud/simple-webapp-mysql
      ports:
        - containerPort: 8080
    - name: logging-agent
      image: splunk/splunk
      ports:
        - containerPort: 8082