apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    type: web-application
spec:
  containers:
    - name: webapp-color
      image: kodekloud/simple-webapp
      envFrom:
        - secretRef:
            name: app-secrets        # This name should be a valid secret-name created using secrets.yaml