apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008 # Has to be a valid range between 30000 and 32767
  selector:
    type: frontend