apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-persistent-volume-claim
spec:
  selector:
    matchLabels:
      name: sample-persistent-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi