---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
spec:
  limits:
    - type: Container
      default:
        cpu: "2"
      defaultRequest:
        cpu: "0.5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit-range
spec:
  limits:
    - type: Container
      default:
        memory: "2Gi"
      defaultRequest:
        memory: "256Mi"