apiVersion: v1
kind: Pod
metadata:
  name: node01
  namespace: test
  labels:
    app: webservice
spec:
  containers:
    - name: rest-web-service
      image: tomcat
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - frontend
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: In
                values:
                  - Large
                  - Medium
              - key: size
                operator: NotIn
                values:
                  - Small