apiVersion: v1
kind: Pod
metadata:
  namespace: dev
  name: nginx-pod
  labels:
    tier: frontend
    application: forms
spec:
  containers:
    - name: nginx-pod
      image: nginx
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: "1"
          memory: "256Mi"
        limits:
          memory: "2Gi"
          cpu: "3"